# Generated by Django 5.0.7 on 2024-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_recipes_user_alter_recipes_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
